name: Builds

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18
          cache: 'npm'

      - run: ./scripts/dev-init.sh

      - name: Build packages
        run: |
          npm -w packages/app-api run build
          npm -w packages/app-mock-gameserver run build
          npm -w packages/app-connector run build
          npm -w packages/lib-apiclient run build
          npm -w packages/lib-components run build
          npm -w packages/lib-config run build
          npm -w packages/lib-db run build
          npm -w packages/lib-gameserver run build
          npm -w packages/lib-http run build
          npm -w packages/lib-util run build
          npm -w packages/lib-queues run build
          npm -w packages/lib-modules run build
          npm -w packages/test run build
          npm -w packages/web-main run build

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      - name: Upload Sourcemaps to Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: web-main
        with:
          sourcemaps: ./packages/web-main/dist
